core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('shop/', views.shop, name='shop'),
    path('set_category/<int:category_id>/', views.set_category_session, name='set_category_session'),
    path('shop/get_toys_by_category/', views.get_toys_by_category, name='get_toys_by_category'),
]

genxtoys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('toy/', include('toy.urls')),
    path('admin/', admin.site.urls),
    path('', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toy/urls.py
from django.urls import path

from . import views

app_name = 'toy'

urlpatterns = [
    # ex: /toy/8/
    path('<int:pk>/', views.detail, name='detail'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from faker import Faker

fake = Faker()

def generate_username_sample():
    prefix = fake.prefix_nonbinary().replace('.', '_')
    first_name = fake.first_name_nonbinary()
    color = fake.color_name()
    random_letter = fake.random_letter()
    random_number = fake.random_number(2)

    return f"{prefix}{first_name}_{color}_{random_letter}{random_number}"

class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=30, help_text='Required', widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-lg',
        'autocomplete':'username'}))
    password = forms.CharField(help_text='Required', widget=forms.PasswordInput(attrs={
        'placeholder': 'Our secret handshake',
        'class': 'w-full py-4 px-6 rounded-lg',
        'autocomplete':'current-password'}))

class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'accept_suggested_username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    INPUT_STYLES = 'w-full py-4 px-6 rounded-lg'


    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.suggested_username = generate_username_sample()
        self.fields['username'].widget.attrs.update({
            'placeholder': f'Choose a cool username, like {self.suggested_username}',
            'class': 'w-full py-4 px-6 rounded-lg'
        })  
    username = forms.CharField(max_length=30, help_text='Required', widget=forms.TextInput(attrs={
        'class': INPUT_STYLES,
        'autocomplete':'username'}))
    accept_suggested_username = forms.BooleanField(required=False, initial=False, widget=forms.CheckboxInput(attrs={
        'id': 'accept-suggested',
        'label': 'Accept suggested username: ',
        'onclick': 'acceptSuggestedName()'}))
    email = forms.EmailField(max_length=254, help_text='Required', widget=forms.EmailInput(attrs={
        'placeholder': 'Where can we spam you?',
        'class': INPUT_STYLES}))
    first_name = forms.CharField(max_length=50, help_text='Required', widget=forms.TextInput(attrs={
        'placeholder': 'What do your friends yell when they see you?',
        'class': INPUT_STYLES}))
    last_name = forms.CharField(max_length=50, help_text='Required', widget=forms.TextInput(attrs={
        'placeholder': 'You know, the name you hide when you\'re famous.',
        'class': INPUT_STYLES,
        'autocomplete':'family-name'}))
    password1 = forms.CharField(help_text='Required', label='Password', widget=forms.PasswordInput(attrs={
        'placeholder': 'Your secret handshake in text form.',
        'class': INPUT_STYLES,
        'autocomplete':'new-password'}))
    password2 = forms.CharField(help_text='Required', label='Repeat password', widget=forms.PasswordInput(attrs={
        'placeholder': 'You sure? Type that secret handshake again.',
        'class': INPUT_STYLES,
        'autocomplete':'new-password'}))

core/views.py
from django.shortcuts import render, redirect
from random import sample

from toy.models import Category, Toy

from .forms import SignupForm


def index(request):
    toys = Toy.objects.filter(stock__gt=0)
    count = toys.count()
    random_toys_indices = sample(range(count), min(3, count))
    toys = [toys[i] for i in random_toys_indices]

    categories = Category.objects.all()
    
    return render(request, 'core/index.html', {
        'categories': categories,
        'toys': toys,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    form = SignupForm()
    suggested_username = form.suggested_username
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/login/')

    return render(request, 'core/signup.html', {
        'form': form,
        'suggested_username': suggested_username,
    })

def logout(request):
    return redirect(request, 'core/index.html')

def shop(request):        
    category_id = request.session.get('selected_category', None)

    if 'selected_category' in request.session:
        del request.session['selected_category']

    if category_id:
        toys = Toy.objects.filter(category_id=category_id, stock__gt=0)
    else:
        toys = Toy.objects.filter(stock__gt=0)

    categories = Category.objects.all()
    return render(request, 'core/shop.html', {
        'categories': categories,
        'toys': toys,
        'selected_category': category_id,
    })

def get_toys_by_category(request):
    category_id = request.GET.get('category')
    toys = Toy.objects.filter(category_id=category_id, stock__gt=0) if category_id else Toy.objects.filter(stock__gt=0)
    return render(request, 'core/toy_list_partial.html', {'toys': toys})

def set_category_session(request, category_id):
    request.session['selected_category'] = category_id
    return redirect('core:shop')

core/templates/core/base.html
<!DOCTYPE html>
{% load static %} 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/htmx.org@1.9.11" integrity="sha384-0gxUXCCR8yv9FM2b+U3FDbsKthCI66oH5IA9fHppQq9DDMHuMauqq1ZHBpJxQ0J0" crossorigin="anonymous"></script>
    <link rel="apple-touch-icon" sizes="180x180" href={% static 'media/favicon/apple-touch-icon.png' %}>
    <link rel="icon" type="image/png" sizes="32x32" href={% static 'media/favicon/favicon-32x32.png' %}>
    <link rel="icon" type="image/png" sizes="16x16" href={% static 'media/favicon/favicon-16x16.png' %}>
    <link rel="manifest" href={% static 'media/favicon/site.webmanifest' %}>

    {% block extra_head %}{% endblock %}

    <title>{% block title %}{% endblock %} | GenX Toys</title>

</head>
<body>
    <nav class="bg-white sticky top-0 z-50 border-b shadow-md" id="nav-bar">
        <div class="mx-auto py-2 px-6 xl:px-0 flex items-center justify-between">
            <div class="menu-left px-4 flex items-center space-x-6">
                <a href="/" class="py-4 text-3xl text-blue-800 font-bold">GenX Toys</a>
                <ul class="flex items-center space-x-4 px-8">
                    <li>
                        <a href="{% url 'core:shop' %}" class="px-4 text-xl font-semibold hover:text-blue-400">Shop</a>
                    </li>
                    <li>
                        <a href="{% url 'core:contact' %}" class="px-4 text-xl font-semibold hover:text-blue-400">Contact</a>
                    </li>
                </ul>
            </div>
            <div class="menu-right px-4 flex items-center space-x-6"> 
                <div
                    hx-get="{% url 'hx_menu_cart' %}"
                    hx-trigger="update-menu-cart from:body, delete-item from:body"
                    hx-swap="innerHTML"
                >

                    {% include 'cart\menu_cart.html'%} 

                </div>
                
                
                {% if request.user.is_authenticated %}
                    <a href="#" class="flex-col flex items-center px-4 text-lg font-semibold hover:text-blue-400">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                            <path fill-rule="evenodd" d="M18.685 19.097A9.723 9.723 0 0021.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 003.065 7.097A9.716 9.716 0 0012 21.75a9.716 9.716 0 006.685-2.653zm-12.54-1.285A7.486 7.486 0 0112 15a7.486 7.486 0 015.855 2.812A8.224 8.224 0 0112 20.25a8.224 8.224 0 01-5.855-2.438zM15.75 9a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z" clip-rule="evenodd" />
                          </svg>
                          <div>Account</div>
                    </a>
                    <a href="{% url 'core:logout' %}" class="flex-col flex items-center px-4 text-lg font-semibold hover:text-blue-400">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                            <path fill-rule="evenodd" d="M7.5 3.75A1.5 1.5 0 006 5.25v13.5a1.5 1.5 0 001.5 1.5h6a1.5 1.5 0 001.5-1.5V15a.75.75 0 011.5 0v3.75a3 3 0 01-3 3h-6a3 3 0 01-3-3V5.25a3 3 0 013-3h6a3 3 0 013 3V9A.75.75 0 0115 9V5.25a1.5 1.5 0 00-1.5-1.5h-6zm10.72 4.72a.75.75 0 011.06 0l3 3a.75.75 0 010 1.06l-3 3a.75.75 0 11-1.06-1.06l1.72-1.72H9a.75.75 0 010-1.5h10.94l-1.72-1.72a.75.75 0 010-1.06z" clip-rule="evenodd" />
                          </svg>
                          <div>Logout</div>
                    </a>
                {% else %}
                <a href="{% url 'core:login' %}" class="flex-col flex items-center px-4 text-lg font-semibold hover:text-blue-400">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 5.25a3 3 0 013 3m3 0a6 6 0 01-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1121.75 8.25z" />
                    </svg>
                    <div>Login</div>                          
                </a>
                <a href="{% url 'core:signup' %}" class="flex-col flex items-center px-4 text-lg font-semibold hover:text-blue-400">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M19 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zM4 19.235v-.11a6.375 6.375 0 0112.75 0v.109A12.318 12.318 0 0110.374 21c-2.331 0-4.512-.645-6.374-1.766z" />
                      </svg>
                    <div>Sign Up</div>                      
                </a>
                {% endif %}
            </div>
        </div>
     
    </nav>
    <div>
        {% block content %}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-f font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">Old-School Toys for Middle-Aged Kids: Because Adulthood Sucks.</p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-400">About</a></li>
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-400">Contact</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-400">Privacy policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-400">Terms of use</a></li>
            </ul>

        </div>
    </footer>

</body>
</html>

core/templates/core/contact.html
{% extends "core/base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}
<h1>This is the contact page...</h1>
{% endblock %}

core/templates/core/index.html
{% extends "core/base.html" %} 
{% load static %} 
{% block title %}Welcome{% endblock %} 

{% block content %}
<header class="w-full bg-cover bg-center py-10" style="height:15rem; background-image: url({% static '/media/HeaderImage.png' %})">
  <div class="max-w-2xl mx-auto text-center bg-gradient-to-b from-gray-900 py-5 rounded-xl">
    <p class="text-xl text-sky-100">
      Relive the past, confuse your kids. Classic toys for unapologetic Xers!
    </p>
    <div class="mt-6">
      <a
        href="#"
        class="px-4 py-2 text-sm font-semibold text-white bg-amber-500 rounded hover:bg-amber-700"
        >Shop Now</a
      >
    </div>
  </div>
</header>
  
  <div class="px-6 py-12 bg-gray-100">
    <h2 class="mb-12 text-2xl text-center">Featured Toys</h2>
    
    <div class="grid grid-cols-3 gap-3">
      {% for toy in toys %}
        <div class="shadow-md bg-white rounded-lg">
          <a href="{% url 'toy:detail' toy.id %}">
            <div class="p-5">
              <img
                src="{% if toy.image %}
                      {{ toy.image.url }}
                  {% else %}../../media/toys_images/placeholder-image.jpg{% endif %}"
                alt="{{ toy.title }}"
                class="w-full object-scale-down h-48"
              />
            </div>
            <div class="p-3 border-t border-gray-300 mx-4 text-center">
              <h2 class="text-xl font-semibold">{{ toy.title }}</h2>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>

  <div class="px-6 py-8 bg-gray-100">
    <h2 class="mb-12 text-2xl text-center">Categories</h2>
    <div class="grid grid-cols-4 gap-3">
      {% for category in categories %}
        <div class="rounded-lg bg-white shadow-md">
          <a href="{% url 'core:set_category_session' category.id %}">
            <div class="p-6">
              <h2 class="text-md font-semibold">{{ category.name }}</h2>
              <p class="text-sm text-gray-500">{{ category.toys.count }} toys</p>      
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl font-semibold py-4">Log in</h1>

    <form method='post' action=".">
        {% csrf_token %}

        <div class="mb-3">
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button type="submit" class="bg-cyan-500 hover:bg-cyan-700 text-white font-bold py-2 px-4 rounded mt-4">
                Log in
            </button>
        </div>
    </form>
</div>

{% endblock %}

core/templates/core/shop.html
{% extends 'core/base.html' %} 
{% load static %} 
{% block title %}Shop{% endblock %} 

{% block extra_head %}
  <script src="{% static 'js/shop.js' %}" defer></script>
{% endblock %}

{% block content %}
<div class="mt-0 px-6 py-12 bg-gray-200">
    <h2 class="mb-8 text-2xl text-center">Shop</h2>

    <div class="mb-8">
        <label for="categorySelect" class="mr-4 ml-2">Filter by category:</label>
        <select id="categorySelect" class="p-2 rounded">
            <option value="">All Categories</option>
            {% for category in categories %}
                <option value="{{ category.id }}" {% if category.id|stringformat:"s" == selected_category|stringformat:"s" %}selected="selected"{% endif %}>
                    {{ category.name }}
                </option>
            {% endfor %}
        </select>
    </div>

    <div class="grid grid-cols-4 gap-4 xl:grid-cols-5" id="toyList">
        {% include 'core/toy_list_partial.html' %}
    </div>

</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl font-semibold py-4">Sign up</h1>

    <form method='post' action=".">
        {% csrf_token %}

        <div class="mb-3">
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>

            <div>
                <label class='mb-3 inline-block text-sm text-gray-600'>{{ form.accept_suggested_username.label }}</label>
                <span>{{ form.accept_suggested_username }}</span>
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{ form.email }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">First name</label><br>
                {{ form.first_name }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Last name</label><br>
                {{ form.last_name }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password1 }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Repeat password</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button type="submit" class="bg-cyan-500 hover:bg-cyan-700 text-white font-bold py-2 px-4 rounded mt-4">
                Sign up
            </button>
        </div>
    </form>
</div>
    {% block javascript %}
    <script>
        function acceptSuggestedName() {
        const checkbox = document.getElementById("accept-suggested");
        const usernameInput = document.getElementById("id_username");
        const suggestedName = "{{ suggested_username }}";  // <-- Use the context variable here

        if (checkbox.checked) {
            usernameInput.value = suggestedName;
        } else {
            usernameInput.value = "";
        }
        }
    </script>
    {% endblock %}

{% endblock %}

core/templates/core/toy_list_partial.html
{% load static %} 
{% for toy in toys %}
<div class="toy bg-white rounded-lg">
    <h3 class="text-center font-semibold py-3 text-lg">{{ toy.title }}</h3>
            <a href="{% url 'toy:detail' toy.id %}">
                <img
                    src="{{ toy.get_image_url }}"
                    alt="{{ toy.name }}"
                    class="w-full h-64 object-scale-down"
                />
            </a>
            <div class="flex items-baseline place-content-evenly p-6 rounded-b-xl">
                <p class="text-xl">${{ toy.price }}</p>
                <span>
                    <!-- Add to Cart button -->
                    {% include 'cart\add_to_cart_btn.html' %}
                </span>
            </div>
</div>
{% endfor %}