cart/urls.py
from django.urls import path

from cart.views import add_to_cart, cart, delete_item, hx_checkout_fill_shipping_from_billing, hx_checkout_shipping_form, update_cart, checkout, hx_checkout_billing_form, hx_menu_cart, hx_cart_total, hx_checkout_btn, hx_cart_items, hx_billing_form_completed

urlpatterns = [
    path('add_to_cart/<str:toy_id>/', add_to_cart, name='add_to_cart'),
    path('update_cart/<str:toy_id>/<str:action>/', update_cart, name='update_cart'),
    path('cart/', cart, name='cart'),
    path('cart/checkout', checkout, name='checkout'),
    path('cart/hx_checkout_billing_form', hx_checkout_billing_form, name='hx_checkout_billing_form'),
    path('cart/hx_billing_form_completed', hx_billing_form_completed, name='hx_billing_form_completed'),
    path('cart/hx_checkout_shipping_form', hx_checkout_shipping_form, name='hx_checkout_shipping_form'),
    path('cart/hx_fill_shipping_from_billing', hx_checkout_fill_shipping_from_billing, name='hx_fill_shipping_from_billing'),
    path('delete_item/<str:toy_id>/', delete_item, name='delete_item'),
    path('hx_menu_cart/', hx_menu_cart, name='hx_menu_cart'),
    path('hx_cart_total/', hx_cart_total, name='hx_cart_total'),
    path('hx_checkout_btn/', hx_checkout_btn, name='hx_checkout_btn'),
    path('hx_cart_items/', hx_cart_items, name='hx_cart_items')
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('shop/', views.shop, name='shop'),
    path('set_category/<int:category_id>/', views.set_category_session, name='set_category_session'),
    path('shop/get_toys_by_category/', views.get_toys_by_category, name='get_toys_by_category'),
]

genxtoys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('toy/', include('toy.urls')),
    path('admin/', admin.site.urls),
    path('', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toy/urls.py
from django.urls import path

from . import views

app_name = 'toy'

urlpatterns = [
    # ex: /toy/8/
    path('<int:pk>/', views.detail, name='detail'),
]

cart/models.py
from django.db import models

cart/forms.py
from django import forms

from order.models import Address
from django.core import validators

INPUT_STYLES = "w-full p-2 border border-gray-300 rounded-md shadow-inner focus:outline-none focus:ring mb"
PHONE_REGEX = r'^(\+61\s?4\d{2}\s?\d{3}\s?\d{3}|04\d{2}\s?\d{3}\s?\d{3}|\(0\d\)\s?\d{4}\s?\d{4}|0\d{8,9})$|^\+?[1-9]\d{7,14}$'


class BillingForm(forms.Form):
    
    def __init__(self, *args, **kwargs):
        super(BillingForm, self).__init__(*args, **kwargs)
        error_class = 'outline outline-offset-0 outline-dotted outline-red-500/25'

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = INPUT_STYLES
            if self.errors.get(field_name):
                field.widget.attrs['class'] += f' {error_class}'

    first_name = forms.CharField(label='First Name', max_length=50, required=True, widget=forms.TextInput(attrs={
        'id': 'billingFirstName',
        'class': INPUT_STYLES}))
    last_name = forms.CharField(label='Last Name', max_length=50, required=True, widget=forms.TextInput(attrs={
        'id': 'billingLastName',
        'class': INPUT_STYLES}))
    street_address = forms.CharField(label='Street Address', max_length=100, required=True, widget=forms.TextInput(attrs={
        'id': 'billingStreetAddress',
        'class': INPUT_STYLES}))
    unit_apt = forms.CharField(label='Unit/Apt', max_length=20, required=False, widget=forms.TextInput(attrs={
        'id': 'billingUnitApt',
        'class': INPUT_STYLES}))
    suburb = forms.CharField(label='Suburb', max_length=50, required=True, widget=forms.TextInput(attrs={
        'id': 'billingSuburb',
        'class': INPUT_STYLES}))
    state = forms.ChoiceField(label='State', choices=[('', 'Select State...')] + list(Address.STATES_CHOICES), required=True, widget=forms.Select(attrs={
        'id': 'billingState',
        'class': INPUT_STYLES}))
    postcode = forms.CharField(label='Postcode', max_length=4, required=True, widget=forms.TextInput(attrs={
        'id': 'billingPostcode',
        'class': INPUT_STYLES}),
        validators=[validators.RegexValidator(r'^\d{4}$', message="* Postcode must be 4 digits.")])
    email = forms.EmailField(label='Email', max_length=254, required=True, widget=forms.EmailInput(attrs={
        'id': 'billingEmail',
        'placeholder': 'test@test.com',
        'class': INPUT_STYLES}),
        validators=[validators.EmailValidator(message="* Please enter a valid email address.")])
    phone = forms.CharField(label='Phone', max_length=15, required=True, widget=forms.TextInput(attrs={
        'id': 'billingPhone',
        'class': INPUT_STYLES}),
        validators=[validators.RegexValidator(PHONE_REGEX, message="* Phone must be in Australian format (04XX XXX XXX or (0X) XXXX XXXX) or international format starting with '+'.")])


class ShippingForm(forms.Form):

    first_name = forms.CharField(label='First Name', max_length=50, required=True, widget=forms.TextInput(attrs={
        'id': 'shippingFirstName',
        'class': INPUT_STYLES}))
    last_name = forms.CharField(label='Last Name', max_length=50, required=True, widget=forms.TextInput(attrs={
        'id': 'shippingLastName',
        'class': INPUT_STYLES}))
    street_address = forms.CharField(label='Street Address', max_length=100, required=True, widget=forms.TextInput(attrs={
        'id': 'shippingStreetAddress',
        'class': INPUT_STYLES}))
    unit_apt = forms.CharField(label='Unit/Apt', max_length=20, required=False, widget=forms.TextInput(attrs={
        'id': 'shippingUnitApt',
        'class': INPUT_STYLES}))
    suburb = forms.CharField(label='Suburb', max_length=50, required=True, widget=forms.TextInput(attrs={
        'id': 'shippingSuburb',
        'class': INPUT_STYLES}))
    state = forms.ChoiceField(label='State', choices=[('', 'Select State...')] + list(Address.STATES_CHOICES), required=True, widget=forms.Select(attrs={
        'id': 'shippingState',
        'class': INPUT_STYLES,
        'placeholder': 'Select State...'}))
    postcode = forms.CharField(label='Postcode', max_length=4, required=True, widget=forms.TextInput(attrs={
        'id': 'shippingPostcode',
        'class': INPUT_STYLES}))


class PaymentForm(forms.Form):
    MONTH_CHOICES = [
        ('', 'Select Month...'),
        ('01', '01 - January'),
        ('02', '02 - February'),
        ('03', '03 - March'),
        ('04', '04 - April'),
        ('05', '05 - May'),
        ('06', '06 - June'),
        ('07', '07 - July'),
        ('08', '08 - August'),
        ('09', '09 - September'),
        ('10', '10 - October'),
        ('11', '11 - November'),
        ('12', '12 - December'),
    ]
    YEAR_CHOICES = [
        ('', 'Select Year...'),
        ('2024', '2024'),
        ('2025', '2025'),
        ('2026', '2026'),
        ('2027', '2027'),
        ('2028', '2028'),
        ('2029', '2029'),
        ('2030', '2030')
    ]

    name_on_card = forms.CharField(label='Name on Card', max_length=50, required=True, widget=forms.TextInput(attrs={
        'id': 'nameOnCard',
        'class': INPUT_STYLES}))
    card_number = forms.CharField(label='Card Number', max_length=16, required=True, widget=forms.TextInput(attrs={
        'id': 'cardNumber',
        'class': INPUT_STYLES}))
    expiry_month = forms.ChoiceField(label='Expiry Month', choices=MONTH_CHOICES, required=True, widget=forms.Select(attrs={
        'id': 'expiryMonth',
        'class': INPUT_STYLES,
        'placeholder': 'Select Month...'}))
    expiry_year = forms.ChoiceField(label='Expiry Year', choices=YEAR_CHOICES, required=True, widget=forms.Select(attrs={
        'id': 'expiryYear',
        'class': INPUT_STYLES,
        'placeholder': 'Select Year...'}))
    cvv = forms.CharField(label='CVV', max_length=3, required=True, widget=forms.TextInput(attrs={
        'id': 'cvv',
        'class': INPUT_STYLES}))

cart/views.py
import time
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect

from .forms import BillingForm, PaymentForm, ShippingForm
from .cart import Cart
from toy.models import Toy


def add_to_cart(request, toy_id):
    cart = Cart(request)
    cart.add(toy_id)

    return render(request, 'cart/menu_cart.html')


def cart(request):
    cart = Cart(request)
    return render(request, 'cart/cart.html', {'cart': cart})


def update_cart(request, toy_id, action=None):
    cart = Cart(request)

    if action == "increase":
        cart.add(toy_id)
    elif action == "decrease":
        cart.add(toy_id, -1)

    toy = Toy.objects.get(pk=toy_id)
    quantity = cart.get_item(toy_id)['quantity']

    cart_item = {
        'toy': {
            'title': toy.title,
            'price': toy.price,
            'stock': toy.stock,
            'image': {
                'url': toy.get_image_url(),
            },
        },
        'quantity': quantity,
        'id': toy_id,
        'total_price': toy.price * quantity,
    }

    response = render(request, 'cart/partials/cart_item.html',
                      {'item': cart_item})

    response['HX-Trigger'] = 'update-menu-cart'

    return response


def delete_item(request, toy_id):
    cart = Cart(request)
    cart.remove(toy_id)

    response = HttpResponse()

    response['HX-Trigger'] = 'delete-item'

    return response


def checkout(request):
    billingForm = BillingForm()
    shippingForm = ShippingForm()
    paymentForm = PaymentForm()
    cart = Cart(request)

    return render(request, 'cart/checkout.html', {'cart': cart, 'billingForm': billingForm, 'shippingForm': shippingForm, 'paymentForm': paymentForm})


def hx_checkout_billing_form(request):
    billingFormCompleted = False
    if request.method == 'POST':
        billingForm = BillingForm(request.POST)
        if billingForm.is_valid():
            billingFormCompleted = True
            request.session['billingForm'] = billingForm.cleaned_data
            print("Cleaned data: ", request.session['billingForm'])
            response = render(request, 'cart/checkout/billing_section.html', {'billingForm': billingForm, 'billingFormCompleted': billingFormCompleted})
            response['HX-Trigger'] = 'billing-form-completed'
            time.sleep(1)
            return response

    return render(request, 'cart/forms/billing_form.html', {'cart': cart, 'billingForm': billingForm, 'billingFormComplete': billingFormCompleted})

def hx_billing_form_completed(request):
    print("Billing form completed event triggered and handled.")
    shippingForm = ShippingForm()
    billingFormCompleted = True
    return render(request, 'cart/checkout/shipping_section.html', {'billingFormCompleted': billingFormCompleted, 'shippingForm': shippingForm})

def hx_checkout_shipping_form(request):
    shippingFormCompleted = False
    if request.method == 'POST':
        print(f"hx_checkout_shipping_form received POST request: {request.POST}")
        shippingForm = ShippingForm(request.POST)
        if shippingForm.is_valid():
            shippingFormCompleted = True
            request.session['shippingForm'] = shippingForm.cleaned_data
            print("Cleaned data: ", request.session['shippingForm'])
            response = render(request, 'cart/checkout/shipping_section.html', {'shippingForm': shippingForm, 'shippingFormCompleted': shippingFormCompleted})
            response['HX-Trigger'] = 'shipping-form-completed'
            time.sleep(1)
            return response

    return render(request, 'cart/forms/shipping_form.html', {'cart': cart, 'shippingForm': shippingForm, 'shippingFormComplete': shippingFormCompleted})

def hx_checkout_fill_shipping_from_billing(request):
    billingForCompleted = True
    same_as_billing = request.GET.get('sameAsBilling') == 'true'
    print(f"same_as_billing: {same_as_billing}")

    if same_as_billing:
        shippingForm = ShippingForm(request.session['billingForm'])
    else:
        shippingForm = ShippingForm()

    return render(request, 'cart/forms/shipping_form.html', {'shippingForm': shippingForm, 'billingFormCompleted': billingForCompleted, 'sameAsBilling': same_as_billing})

def hx_menu_cart(request):
    return render(request, 'cart/menu_cart.html')


def hx_cart_total(request):
    return render(request, 'cart/partials/cart_total.html')


def hx_checkout_btn(request):
    return render(request, 'cart/partials/checkout_btn.html')


def hx_cart_items(request):
    cart = Cart(request)
    return render(request, 'cart/partials/cart_items.html', {'cart': cart})

cart/templates/cart/partials/cart_item.html
{% load static %}
<div class="relative cart-item grid grid-cols-12 gap-4 my-3" id="cart-item-{{ item.id }}">
    <div class="cart-item-image col-span-2">
        <a href="#">
            <img
                src="{% if item.toy.image.url %}
                        {{ item.toy.image.url }}
                    {% else %}../../media/toys_images/placeholder-image.jpg{% endif %}"
                alt="{{ item.toy.title }}"
                class="w-full h-32 object-scale-down hover:shadow-lg rounded-lg"
            />
        </a>
    </div>
    <div class="cart-item-title col-span-3 pt-3 text-center self-center">
        <p>{{ item.toy.title }}</p>
    </div>
    <div class="cart-item-price relative col-span-2 text-center self-center mb-3">
        <div class="text-xs absolute font-thin">Price:</div>
        <p class="pt-5">$ {{item.toy.price}}</p>
    </div>
    <div class="cart-item-quantity col-span-2 flex items-center justify-center space-x-2 group relative mt-2">
        {% if item.quantity == 1 %}
            <div 
                id="decrease-quantity-toy-{{ item.id }}"
                class="opacity-40 cursor-not-allowed">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>                              
                </div>
        {% else %}
            <a 
                id="decrease-quantity-toy-{{ item.id }}"
                href="#"
                hx-get="{% url 'update_cart' item.id 'decrease' %}"
                hx-target="#cart-item-{{ item.id }}"
                hx-swap="outerHTML">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 hover:text-rose-600">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>                              
            </a>
        {% endif %}
        <span>{{item.quantity}}</span>
        {% if item.quantity == item.toy.stock %}
            <div 
                id="increase-quantity-toy-{{ item.id }}"
                class="relative group">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 opacity-40">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>                                                            
            </div>
            <div class="opacity-0 text-xs text-red-600 group-hover:opacity-100 transition-opacity duration-1000 ease-in-out break-normal mt-12 absolute">Max reached!</div>
        {% else %}
            <a 
                id="increase-quantity-toy-{{ item.id }}"
                href="#"
                hx-get="{% url 'update_cart' item.id 'increase' %}"
                hx-target="#cart-item-{{ item.id }}"
                hx-swap="outerHTML">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 hover:text-lime-500">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>                                                            
            </a>
        {% endif %}
    </div>
    <div class="cart-item-subtotal relative col-span-2 text-center self-center mb-3">
        <div class="text-xs absolute font-thin">Subtotal:</div>
        <p class="pt-5">$ {{item.total_price}}</p>
    </div>
    <div class="delete-button relative col-span-1 text-center self-center static">
        <a id="delete-button-{{ item.id }}" 
            href="#" 
            onclick="toggleConfirmation({{ item.id }}); return false;"
            class="text-zinc-800 hover:text-red-600"
            >
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                <path stroke-linecap="round" 
                stroke-linejoin="round" 
                d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
              </svg>
        </a>
    </div>
    <div id="confirmation-{{ item.id }}"
        class="grid grid-cols-2 gap-x-5 gap-y-1 rounded-lg absolute w-88 bottom-0 right-4 bg-rose-50 px-4 mb-1 hidden">
        <p class="text-sm col-span-2">Are you sure you want to remove this item?</p>

        <a
            class="text-white text-md text-center bg-red-500 hover:bg-red-600 px-2 rounded-md col-span-1 mb-2"
            href="#"
            hx-get="{% url 'delete_item' item.id %}"
            hx-target="#cart-item-{{ item.id }}"
            hx-swap="delete">
            Remove
        </a>

        <a
            class="text-white text-md text-center bg-gray-400 hover:bg-gray-500 px-2 rounded-md col-span-1 mb-2"
            onclick="toggleConfirmation({{ item.id }}); return false;"
            href="#"
            >
            Cancel
        </a>
    </div>
    <div class="col-span-12"><hr></div>
</div>
<script src="{% static 'js/cart_item.js' %}"></script>

cart/templates/cart/partials/cart_items.html
{% load static %} 
{% if cart|length == 0 %}

    <div class="flex justify-center items-center mx-10 h-80">
        <img src="{% static 'media/koala_cart.png' %}" alt="Koala" class="h-72 w-auto mr-4">
        <div class="text-center mb-12">
            <h2 class="text-2xl mb-2">Your cart is empty</h2>
            <a href="{% url 'core:shop' %}" class="text-blue-500 underline">Go back to Shop</a>
        </div>
    </div>

{% else %}

{% for item in cart %}
    {% include 'cart/partials/cart_item.html' %}
{% endfor %}

{% endif %}

cart/templates/cart/partials/cart_total.html
$ {{cart.get_total}}

cart/templates/cart/partials/checkout_btn.html
{% if cart|length > 0 %}
<a
                href="{% url 'checkout' %}"
                class="inline-block px-4 py-2 rounded-xl bg-purple-500 hover:bg-purple-700 text-white"
                >Checkout</a
            >
{% else %}
<div
                href="#"
                class="inline-block px-4 py-2 rounded-xl bg-gray-300 text-gray-500"
                >Checkout</div
            >
{% endif %}

cart/templates/cart/partials/chevron.html
<svg xmlns="http://www.w3.org/2000/svg" 
    fill="none" 
    viewBox="0 0 24 24" 
    stroke-width="2.5" 
    stroke="currentColor" 
    hx-trigger="billing-form-completed from:body"
    hx-get="{% url 'hx_billing_form_completed' %}"
    hx-swap="outerHTML"
    class="chevron w-6 h-6 stroke-violet-600 {% if not billingFormCompleted %}rotate-90{% endif %}">
    <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
</svg>